<?php
	// Resilient IP client installation tool.
	// (C) 2016 CubicleSoft.  All Rights Reserved.

	if (!isset($_SERVER["argc"]) || !$_SERVER["argc"])
	{
		echo "This file is intended to be run from the command-line.";

		exit();
	}

	// Temporary root.
	$rootpath = str_replace("\\", "/", dirname(__FILE__));

	require_once $rootpath . "/support/cli.php";
	require_once $rootpath . "/support/resilient_ip_functions.php";

	// Process the command-line options.
	$options = array(
		"shortmap" => array(
			"?" => "help"
		),
		"rules" => array(
			"help" => array("arg" => false)
		),
		"userinput" => "="
	);
	$args = CLI::ParseCommandLine($options);

	if (isset($args["opts"]["help"]))
	{
		echo "Resilient IP client installation command-line tool\n";
		echo "Purpose:  Installs the resilient IP client.\n";
		echo "\n";
		echo "This tool is question/answer enabled.  Just running it will provide a guided interface.  It can also be run entirely from the command-line if you know all the answers.\n";
		echo "\n";
		echo "Syntax:  " . $args["file"] . " [options]\n";
		echo "\n";
		echo "Example:\n";
		echo "\tphp " . $args["file"] . "\n";

		exit();
	}

	$config = RESIP_LoadConfig();

	if (!isset($config["apikey"]))
	{
		$config["apikey"] = CLI::GetUserInputWithArgs($args, "apikey", "Master API key", false, "The master API key is generated by the server installer.  Copy and paste it here.");

		RESIP_SaveConfig($config);
	}

	if (!isset($config["host"]))
	{
		$config["host"] = CLI::GetUserInputWithArgs($args, "host", "Resilient IP host", false, "For security reasons, an IP address is preferred for the host.  Regular DNS responses can be spoofed.");

		RESIP_SaveConfig($config);
	}

	if (!isset($config["session_port"]))
	{
		$port = (int)CLI::GetUserInputWithArgs($args, "session_port", "Session server port", "31265");
		if ($port < 0 || $port > 65535)  $port = 31265;
		$config["session_port"] = $port;

		RESIP_SaveConfig($config);
	}

	if (!isset($config["resip_protocol"]))
	{
		$protocols = array(
			"udp" => "UDP/IP",
			"tcp" => "TCP/IP"
		);

		$config["resip_protocol"] = CLI::GetLimitedUserInputWithArgs($args, "protocol", "Resilient IP server protocol", "udp", "Available protocols:", $protocols, true);

		RESIP_SaveConfig($config);
	}

	if (!isset($config["resip_port"]))
	{
		$port = (int)CLI::GetUserInputWithArgs($args, "resip_port", "Resilient IP server port", "31266");
		if ($port < 0 || $port > 65535)  $port = 31266;
		$config["resip_port"] = $port;

		RESIP_SaveConfig($config);
	}

	if (!isset($config["prefer_ipv6"]))
	{
		$config["prefer_ipv6"] = CLI::GetYesNoUserInputWithArgs($args, "prefer_ipv6", "Prefer IPv6", "N");

		RESIP_SaveConfig($config);
	}

	echo "\n";
	echo "**********\n";
	echo "Configuration file is located at '" . $rootpath . "/config.dat'.  It can be manually edited.\n\n";
	echo "Run 'client.php' to start the client.\n";
	echo "**********\n\n";

	echo "Done.\n";
?>